#+HTML_HEAD: <link rel="stylesheet" href="../../static/style.css">
#+HTML_HEAD: <link rel="icon" href="../../static/projects/cetus/favicon.png" type="image/png">
#+EXPORT_FILE_NAME: index
#+TITLE: Cetus

Cetus is a simple wallpaper management tool written in Go. It supports multiple
sources for fetching the background.

| Project Home  | [[https://andinus.nand.sh/projects/cetus/][Cetus]]           |
| Source Code   | [[https://framagit.org/andinus/cetus][Andinus / Cetus]] |
| GitHub Mirror | [[https://github.com/andinus/cetus][Cetus - GitHub]]  |

*Note*: Cetus is a work in-progress & many features are yet to be implemented.
This whole project was changed multiple times, previous versions have had
support for services like Unsplash Source & Wallhaven. I'm working on this
because I want my desktop to have a new wallpaper everyday.

*Note*: Services were split because they didn't have much in common and it's
easier to maintain when they're split. The cetus command that bundled services
will stay as is so as to not break scripts, it will be dropped in v0.6.

Cetus v0.5 will support NASA Astronomy Picture of the Day & Bing Photo of the
Day, I may add support for other services later. Both sources are very easy to
work with, I personally like NASA APOD & fallback to BPOD only when it's not an
image (somtimes they choose a video for APOD).

Currently the only dependency is [[https://feh.finalrewind.org/][feh]], it is used to set the background. It
doesn't support some desktop environments but should work fine many others. I
plan to add support for unsupported DEs too provided they're not hard to
implement.

Also the code is not so good, I couldn't think of a good way to structure it. If
you have a better idea then please let me know.

* Demo
I just run some cetus commands on my computer, nothing fancy. I'll make better
demo videos someday.

| Version | Video                                                                |
|---------+----------------------------------------------------------------------|
| v0.5.1  | https://diode.zone/videos/watch/0f94f5df-432d-491b-b7ab-57129213e47f |
| v0.5.0  | https://diode.zone/videos/watch/82b4f048-47aa-4012-8281-61e23840a598 |
| v0.4.6  | https://diode.zone/videos/watch/965bb7a4-029a-4584-a40d-241959d1aced |
| v0.4.1  | https://diode.zone/videos/watch/a52cc728-93e5-4bba-9375-752e1dba306d |
| v0.3.1  | https://diode.zone/videos/watch/0808c512-315a-4dab-9526-4a537e8c3257 |
| v0.2.0  | https://diode.zone/videos/watch/12db31e1-3517-4888-ad06-55f3859447a1 |
